version: '3.6'

services:
  db:
    image: postgres:14
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./main:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080