version: '3'

services:
  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    ports:
      - "8000:80"

  node1:
    image: nginx:1.24.0-alpine
    container_name: node1
    ports:
      - "80"

  node2:
    image: nginx:1.24.0-alpine
    container_name: node2
    ports:
      - "80"

