version: '3'

services:
  primary:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - primary_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  replica:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: primary
      POSTGRES_PORT: 5432
      POSTGRES_MASTER_USER: postgres
      POSTGRES_MASTER_PASSWORD: postgres
    volumes:
      - replica_data:/var/lib/postgresql/data

volumes:
  primary_data:
  replica_data:
