version: '3'

networks:
  proxy:
    driver: bridge

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx/
    ports:
      - 8080:8080
    networks:
      - proxy
